### ISSUE TITLE
Suggestion: Add support for editor.bracketPairColorization.enabled

### ISSUE THREAD

**Issue by fleps** [ArthurLobopro/easy-codesnap#54]
Love this extension, IMO it's the best and most complete out there!

Would it be possible to support `"editor.bracketPairColorization.enabled"`, so the brackets colors follow those rules?

It became very common to have this as true, but right now the extension doesn't use the colors configured for it, it follows the theme own colors instead for the brackets.

Unless this is not possible and a limitation on what this type of extension can do.

**Comment by ArthurLobopro** [comment]
@fleps Hello! Thank you for the suggestion! 

The extension can copy your code keeping the colors copying as HTML using the command `editor.action.clipboardCopyWithSyntaxHighlightingAction`. Unfortunately, this command don't pick the bracket colors, keeping the colors from your current theme.

This would be a really great addition, but I can't do this because the vscode copy command don't copy the modified bracket colors.

If you know an open source extension that can do that, please leave the repository link here, so I can take a look and maybe somehow add this feature
