### ISSUE TITLE
Corners aren't transparent

### ISSUE THREAD

**Issue by nab138** [ArthurLobopro/easy-codesnap#74]
When using rounded corners and window capture mode, the background isn't fully transparent (can be hard to see in github dark mode). I even set the background color to be #fff0 and checked the transparent background setting.

Ex:
![image](https://github.com/user-attachments/assets/17d402f2-be2d-489e-bde1-c37585e6ef7c)

**Comment by ArthurLobopro** [comment]
Hi @nab138 , I think this happens because boxShadow config

![image](https://github.com/user-attachments/assets/aa638643-2c0d-45f3-8ac5-dd3a58e057fd)
![code](https://github.com/user-attachments/assets/4d210eb9-ec08-4708-871a-4eff715ab930)

![image](https://github.com/user-attachments/assets/c1cebbdc-d972-417e-83b5-0b860474c327)
![code2](https://github.com/user-attachments/assets/3e6a5c14-c4b8-431a-aa60-ed239c92ab6f)

It's very hard to see (I am using Github theme on VSCode). But without boxShadow this don't happen.

I will fix it in the next version. Thank you for warning me!
